const swaggerAutogen = require('swagger-autogen')()

const doc = {
    info: {
        version: "0.0.1",
        title: process.env.SERVER_NAME,
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:5000",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
}

const outputFile = './docAutoGen/swaggerOutput.json'
const endpointsFiles = ['./src/controllers/routes']

module.exports = swaggerAutogen(outputFile, endpointsFiles, doc);
